apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: otd
resources:
  - ../../base
images:
  - name: ghcr.io/sdhayanand/tb-jms-to-pubsub-bridge
    newName: us-central1-docker.pkg.dev/PROJECT_ID/tb-otd/jms-to-pubsub-bridge
    newTag: latest
# deploy-gcp.yml runs: kustomize edit set image ... and sed -i "s/PROJECT_ID/$GCP_PROJECT_ID/g"
