apiVersion: v1
kind: Service
metadata:
  name: jms-to-pubsub-bridge
spec:
  selector:
    app.kubernetes.io/name: jms-to-pubsub-bridge
  ports:
    - name: http
      port: 8090
      targetPort: http
