apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: otd
commonLabels:
  app.kubernetes.io/name: pubsub-to-jms-bridge
  app.kubernetes.io/part-of: tb-otd
  app.kubernetes.io/component: migration-bridge
resources:
  - serviceaccount.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - pdb.yaml
