apiVersion: v1
kind: Service
metadata:
  name: pubsub-to-jms-bridge
spec:
  selector:
    app.kubernetes.io/name: pubsub-to-jms-bridge
  ports:
    - name: http
      port: 8091
      targetPort: http
